[phases.setup]
nixPkgs = ["python311", "nodejs-18_x", "yarn"]

[phases.install]
cmds = [
  "pip install -r backend/requirements.txt",
  "cd frontend && yarn install --frozen-lockfile"
]

[phases.build]
cmds = ["cd frontend && yarn build"]

[start]
cmd = "cd backend && uvicorn server:app --host 0.0.0.0 --port $PORT"
