[build]
builder = "NIXPACKS"
buildCommand = "cd frontend && yarn install && yarn build"

[deploy]
startCommand = "cd backend && uvicorn server:app --host 0.0.0.0 --port $PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
